# Generated by Django 3.0.6 on 2020-06-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artcollection',
            name='slug',
            field=models.SlugField(default='starrynight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artpiece',
            name='slug',
            field=models.SlugField(default='testpiece1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codeproject',
            name='slug',
            field=models.SlugField(default='testproject1'),
            preserve_default=False,
        ),
    ]
