# Generated by Django 3.0.6 on 2020-05-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproject',
            name='thumbnail',
            field=models.ImageField(upload_to='codeProjectThumbnails'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='thumbnail',
            field=models.ImageField(upload_to='imageCollectionThumbnails'),
        ),
    ]
