# Generated by Django 3.0.6 on 2020-07-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200626_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
