# Generated by Django 3.0.6 on 2020-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200527_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproject',
            name='thumbnail',
            field=models.ImageField(upload_to='codeProjectThumbnails/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='thumbnail',
            field=models.ImageField(upload_to='imageCollectionThumbnails/'),
        ),
    ]
