# Generated by Django 3.0.6 on 2020-07-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='ArtPieces/'),
        ),
    ]
